### ISSUE TITLE
Is it `tljh` or `TLJH`?

### ISSUE THREAD

**Issue by choldgraf** [yuvipanda/the-littlest-jupyterhub#21]
I'm a fan of `tljh` myself :-)

**Comment by yuvipanda** [comment]
I've been using 'tljh' when using it in the commandline, but TLJH when using in the docs as an abbreviation.

**Comment by yuvipanda** [comment]
So it's context dependent, no?

**Comment by choldgraf** [comment]
ahh I see - I just noticed both usages in the docs and figured I'd ask. I didn't notice if it was a systematic usage in one context or another.
