### ISSUE TITLE
Google cloud instructions resulted in a non-accessible JupyterHub

### ISSUE THREAD

**Issue by choldgraf** [yuvipanda/the-littlest-jupyterhub#23]
The gcloud instructions gave me a JupyterHub that wasn't accessible at the external IP:

Here's the link (I created it in binder sandbox so we could share instance info) https://console.cloud.google.com/compute/instancesDetail/zones/us-west1-b/instances/test-jupyterhub?project=binder-sandbox-194621

It seems like JupyterHub is running (if I SSH into it and run `sudo systemctl restart jupyterhub
` I see ` JupyterHub is now running at http://:80/`) but hitting the external IP at https://35.185.197.86/ isn't responding.

**Comment by yuvipanda** [comment]
@choldgraf you were accessing it at https, which doesn't work yet. the HTTP link works: http://35.185.197.86

**Comment by yuvipanda** [comment]
I think clicking it on the gcloud console automatically sends you to https, which is almost never going to work with an IP address.

**Comment by choldgraf** [comment]
ah ha - ok cool, that worked. Updated #24 with some text improvements to this effect. One weird thing is that I had stopped the VM to save costs. When I restarted it, the external IP was now different.

**Comment by yuvipanda** [comment]
@choldgraf yeah, by default you get ephemeral external IPs that change all the time. You can 'reserve' it with https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address if you want.

**Comment by choldgraf** [comment]
ah good to know - is that standard procedure for all providers? If so, perhaps it's worth having that in the "guide" section

**Comment by yuvipanda** [comment]
@choldgraf good question! I know it's the case for Google, unsure about others. IIRC Jetstream nor Digital Ocean do this I think.
