### ISSUE TITLE
TLJH login failures

### ISSUE THREAD

**Issue by JuanCab** [yuvipanda/the-littlest-jupyterhub#28]
I managed to get logged in to my TLJH server via the web browser.  Played around with it and installed some packages via the terminal.  However once I logged out it will not let me log back in again.  JupyterHub is insisting I am entering the wrong username and password when the same username and password work via SSH.  

Syslog states

> Jul  9 19:32:47 jupyterhub python3[859]: [W 2018-07-09 19:32:47.993 JupyterHub base:503] Failed login for juan

Attempted solutions
- Checked `/opt/tljh/config.yaml` for problems, appears intact with contents
```
users:
  admin:
    - juan
```
- Restarting server software didn't help.
- Restarting the VM entirely didn't help.
- Changing user password from the command line and trying the new password didn't help.
- Changed web browsers, it didn't help.

So I have the login page, but it is not recognizing the account.  This suggests a serious potential problem with how JupyterHub is authenticating, since it appears to have broken.

**Comment by yuvipanda** [comment]
Heya! Thank you very much for 

TLJH is not using PAM authentication, it has its own authentication set up. Currently that is set up with https://github.com/yuvipanda/jupyterhub-firstuseauthenticator - so the password you used when logging in for the very first time is the JupyterHub password for the user. If you wanna clear it, deleting `/opt/tljh/hub/state/passwords.*` should work.

We'll add support for [other authenticators](https://github.com/jupyterhub/jupyterhub/wiki/Authenticators) soon. I'll also be changing the user account creation process soon to not re-use any already existing system accounts (see #9), and write more docs to make it clear your Unix password isn't used by JupyterHub at all.

I hope this makes sense?

**Comment by JuanCab** [comment]
Yeah, makes more sense now.  It would be appreciated if other authenticators could be supported.  It does appear when I created the account in JupyterHub, it created the user directory on the linux side.  Is there any 'default directory it clones when doing this?  I am hoping for a way to have students sign in with their own accounts (with an authenticator) and having it clone a directory of notebooks for them to run.

**Comment by yuvipanda** [comment]
@JuanCab yep, that's an extremely common use case! I will probably install this extension: https://github.com/data-8/nbgitpuller by default, since it makes it extremely easy to distribute materials to students continuously by having them click a URL.

Which authenticator would you like to see supported first?

**Comment by yuvipanda** [comment]
I'll probably also start creating user home directories under `/opt/tljh/homes` or something too.

**Comment by JuanCab** [comment]
nbgitpuller sounds like exactly what we would need.

As for the authenticator we use on this campus, I believe it is Active Directory (unfortunately).

**Comment by JuanCab** [comment]
I think creating separate home directories makes sense, although maybe where it does it should be configurable.

**Comment by yuvipanda** [comment]
Separate home directories are created, under /home for now. Usernames are prefixed with 'jupyter-'. http://the-littlest-jupyterhub.readthedocs.io/en/latest/topic/security.html has documentation!

**Comment by JuanCab** [comment]
Thanks!  I ended up using `/etc/skel` for the 'resource' directory because it is more friction free (students won't see it happen).

**Comment by snailkn** [comment]
I have the same problem, but can't find the file `/opt/tljh/hub/state/passwords.*`, is there any other solution to reset the password of a admin user when login failed?

**Comment by KarelMacek** [comment]
I was wondering why this is closed. The problem persists, at least in my case.
